spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/video?useUnicode=true&characterEncoding=utf8
    username: root
    password: '01022074992'
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        show-sql: false
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
